import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createApp} from '../server/app.js';
import {validateBrief,validateRanking,isolatedDocument} from '../src/lib/validation.js';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const origin='http://localhost:5173';
async function running(options,fn){const {app,close}=createApp({database:':memory:',origin,...options});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url='http://127.0.0.1:'+server.address().port;try{await fn(async(path,body,headers={})=>fetch(url+path,body===undefined?{}:{method:'POST',headers:{origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)}));}finally{await new Promise(r=>server.close(r));close();}}
const payload={system:'generate ideas',prompt:'operations',max_tokens:1500};
test('live requests require authentication, correct origin and bounded tokens',async()=>{let calls=0;await running({accessKey:'a'.repeat(24),apiKey:'fake',upstreamFetch:()=>{calls++;throw Error();}},async request=>{assert.equal((await request('/api/agent',payload)).status,401);assert.equal((await request('/api/login',{accessKey:'wrong'})).status,401);assert.equal((await request('/api/login',{accessKey:'a'.repeat(24)},{origin:'https://evil.example'})).status,403);const login=await request('/api/login',{accessKey:'a'.repeat(24)});const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await request('/api/agent',{...payload,max_tokens:9000},{cookie})).status,400);assert.equal((await request('/api/agent',payload,{cookie:cookie+'broken'})).status,401);assert.equal(calls,0);});});
test('fictional full flow never calls upstream and ranking keeps IDs',async()=>running({demo:true,upstreamFetch:()=>{throw Error('Paid call');}},async request=>{const brief=validateBrief(JSON.parse((await (await request('/api/agent',payload)).json()).content[0].text));const ranked=JSON.parse((await (await request('/api/agent',{...payload,system:'skeptic_note',prompt:'Ideas to score:\n'+JSON.stringify(brief.ideas)})).json()).content[0].text);assert.equal(validateRanking(ranked,brief.ideas).length,5);const built=await (await request('/api/agent',{...payload,system:'architect_note'})).json();assert.match(built.content[0].text,/Add task/);}));
test('durable budgets survive server restart',async()=>{const dir=mkdtempSync(join(tmpdir(),'idea-budget-'));try{const opts={demo:true,database:join(dir,'quota.sqlite')};await running(opts,async request=>{for(let n=0;n<20;n++)assert.equal((await request('/api/agent',payload)).status,200);});await running(opts,async request=>assert.equal((await request('/api/agent',payload)).status,429));}finally{rmSync(dir,{recursive:true});}});
test('truncation fails without automatic retries',async()=>{let calls=0;await running({accessKey:'a'.repeat(24),apiKey:'fake',upstreamFetch:async()=>{calls++;return new Response(JSON.stringify({stop_reason:'max_tokens'}));}},async request=>{const login=await request('/api/login',{accessKey:'a'.repeat(24)});const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await request('/api/agent',payload,{cookie})).status,502);assert.equal(calls,1);});});
test('ranking rejects unknown, duplicated, missing IDs and invalid scores',()=>{const ideas=[{id:'a'},{id:'b'}];const ranked=[{id:'a',score:9,verdict:'ok'},{id:'b',score:8,verdict:'ok'}];for(const rows of [[ranked[0]], [ranked[0],ranked[0]], [{...ranked[0],id:'c'},ranked[1]], [{...ranked[0],score:11},ranked[1]]])assert.throws(()=>validateRanking({skeptic_note:'Example',ranked:rows},ideas));});
test('preview CSP blocks connections and forms',()=>{assert.match(isolatedDocument('<script>fetch("/api")</script>'),/connect-src 'none'/);assert.match(isolatedDocument(''),/form-action 'none'/);});
